GET   https://localhost:7071/api/Product/orders/supplier/company/1/603212216
Content-Type: application/json


{
  "productName": "Papas",
  "supplierName": "Prueba",
  "purchaseDate": "2024-05-26T18:55:15.639Z",
  "costPrice": 100000,
  "branches": [
    {
      "branchName": "Alimentos123",
      "quantity": 5
    }
  ]
}