GET  https://localhost:7071/api/Product/branches/company/8
Content-Type: application/json

{
  "id": 56743,
  "name": "njj8",
  "supplierType": "persona",
  "address": "string",
  "phone": "string",
  "email": "string",
  "urlPage": "string",
  "serviceType": "Proveedor de servicios"
}