GET  https://localhost:7071/api/Supplier/company/1
Content-Type: application/json

{
  "id": 603212217,
  "name": "nombre",
  "supplierType": "Proveedor de productos",
  "address": "string",
  "phone": "string",
  "email": "string",
  "urlPage": "string",
  "serviceType": "Proveedor de servicios"
}